version: "3.8"
services:
  web:
    command: sh -c '/app/bin/work_api eval "WorkApi.Release.migrate" && /app/bin/server'
    build:
      context: .
      args: 
        API_USER: ${API_USER}
        API_PASSWORD: ${API_PASSWORD}
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE} 
    ports: 
      - 4001:4001
    environment:
      API_USER: ${API_USER}
      API_PASSWORD: ${API_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE} 
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports: 
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
